name: Build Android APK
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Flet
        run: pip install flet

      - name: Build APK avec Flet
        env:
          FLET_NON_INTERACTIVE: true
        run: flet build apk --android-permissions android.permission.ACCESS_FINE_LOCATION=True android.permission.ACCESS_COARSE_LOCATION=True android.permission.INTERNET=True
